// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwCSrkJrrCkFEBIfkqduYj3FwPfq3BGeY',
    appId: '1:48331029178:web:b22e3bd570eca817e52083',
    messagingSenderId: '48331029178',
    projectId: 'fatorfit',
    authDomain: 'fatorfit.firebaseapp.com',
    databaseURL: 'https://fatorfit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatorfit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQtRVrulYbIg4szTL47h4nuquDXD4td0',
    appId: '1:48331029178:android:8022a2a658672d06e52083',
    messagingSenderId: '48331029178',
    projectId: 'fatorfit',
    databaseURL: 'https://fatorfit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatorfit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2GCie-lgVVG5UfcoCFCCrSMaP2jV7rn8',
    appId: '1:48331029178:ios:47bc3d44875419b8e52083',
    messagingSenderId: '48331029178',
    projectId: 'fatorfit',
    databaseURL: 'https://fatorfit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatorfit.appspot.com',
    androidClientId: '48331029178-f4s6jhn4q3jknnca2vl3eo8og7polsm5.apps.googleusercontent.com',
    iosClientId: '48331029178-anc0hbumkvvt5103gq5rasmc5eb15a5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fatorfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2GCie-lgVVG5UfcoCFCCrSMaP2jV7rn8',
    appId: '1:48331029178:ios:47bc3d44875419b8e52083',
    messagingSenderId: '48331029178',
    projectId: 'fatorfit',
    databaseURL: 'https://fatorfit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatorfit.appspot.com',
    androidClientId: '48331029178-f4s6jhn4q3jknnca2vl3eo8og7polsm5.apps.googleusercontent.com',
    iosClientId: '48331029178-anc0hbumkvvt5103gq5rasmc5eb15a5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fatorfit',
  );
}
